{{- if .Values.locustJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-tests
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: locust-tests
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: locust-tests
    spec:
      containers:
        - name: locust-runner
          image: {{ .Values.locustJob.image }}
          env:
            - name: LOCUST_MODE
              value: "{{ .Values.locustJob.mode }}"
            - name: LOCUST_USERS
              value: "{{ .Values.locustJob.users }}"
            - name: LOCUST_SPAWN_RATE
              value: "{{ .Values.locustJob.spawnRate }}"
            - name: LOCUST_RUN_TIME
              value: "{{ .Values.locustJob.runTime }}"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Never
{{- end }}
